"""
GameDataLoader for Python - manages game data file paths across versions

IMPORTANT: When generating static game data, the adjacency data must be generated FIRST:
  1. Run create-adjacency-data.py to generate adjacency-data.csv and location-river-colors.json
  2. Then run generate_static_game_data.py which depends on those files
"""

import os
import re
from typing import Dict, List, Optional
from dataclasses import dataclass

GameVersion = str  # e.g., "0.0.11"


@dataclass
class GameDataFiles:
    """Paths to game data files for a specific version"""
    locations_map: str
    rivers_map: str
    ports_file: str
    location_classification: str
    location_data: str
    provinces_data: str
    locations_color_mapping: str
    locations_city_coordinates: str
    pops_file: str
    roads_file: str
    development_file: str
    cities_buildings_file: str
    adjacency_data: str  # Generated by create-adjacency-data.py
    river_colors: str  # Generated by create-adjacency-data.py
    countries_file: str
    special_adjacency_file: str
    computed_river_classification_file: str
    town_setup_file: str


class GameDataLoader:
    """
    Loads game data files for a specific version, with fallback to closest previous version.
    Similar to the TypeScript GameDataLoader class.
    """
    
    BASE_FOLDER_NAMES = {
        'locations_map': 'world_map',
        'rivers_map': 'river_map',
        'ports_file': 'ports',
        'location_classification': 'locations_classification',
        'location_data': 'locations_data',
        'provinces_data': 'provinces_data',
        'locations_color_mapping': 'locations_color_mapping',
        'locations_city_coordinates': 'locations_city_coordinates',
        'pops_file': 'game_setup',
        'roads_file': 'game_setup',
        'development_file': 'game_setup',
        'cities_buildings_file': 'game_setup',
        'countries_file': 'game_setup',
        'special_adjacency_file': 'special_adjacency_file',
        'computed_river_classification_file': 'computed_river_classification',
        'town_setup_file': 'town_setups'
    }
    
    FILE_NAMES = {
        'locations_map': 'locations.png',
        'rivers_map': 'rivers.png',
        'ports_file': 'ports.csv',
        'location_classification': 'default.map',
        'location_data': 'location_templates.txt',
        'provinces_data': 'definitions.txt',
        'locations_color_mapping': '00_default.txt',
        'locations_city_coordinates': 'generated_map_object_locators_city.txt',
        'pops_file': '06_pops.txt',
        'roads_file': '09_roads.txt',
        'development_file': '14_development.txt',
        'cities_buildings_file': '07_cities_and_buildings.txt',
        'countries_file': '10_countries.txt',
        'special_adjacency_file': 'adjacencies.csv',
        'computed_river_adjacency_file': 'computed_river_adjacencies.csv',
        'computed_river_classification_file': 'river_layer_classification.csv',
        'town_setup_file': '00_default.txt'
    }
    
    # Files generated by computation scripts (stored in tools/output/{version}/)
    COMPUTED_OUTPUT_FILES = {
        'adjacency_data': 'adjacency-data.csv',
        'river_colors': 'location-river-colors.json',
    }
    
    def __init__(self, folder_path: Optional[str] = None) -> None:
        """
        Initialize the loader.
        
        Args:
            folder_path: Root path to game_data folder. If None, uses parent directory of cwd + 'game_data'
        """
        if folder_path is None:
            # Go up one directory from tools/ to project root, then into game_data
            script_dir = os.path.dirname(os.path.abspath(__file__))
            project_root = os.path.dirname(script_dir)
            self.folder_path = os.path.join(project_root, 'game_data')
        else:
            self.folder_path = folder_path
    
    @staticmethod
    def get_closest_version(available_versions: List[str], target_version: GameVersion) -> str:
        """
        Get the target version if found, or the closest previous version.
        
        Args:
            available_versions: List of available semver versions (e.g., ["0.0.11", "0.1.0"])
            target_version: The desired version
            
        Returns:
            The matching or closest previous version
            
        Raises:
            ValueError: If no suitable version is found
        """
        if target_version in available_versions:
            return target_version
        
        closest_match = None
        
        for version in available_versions:
            # Validate semver format
            if not re.match(r'[0-9]+\.[0-9]+\.[0-9]+', version):
                continue
            
            # We count on semver versions being alphabetically ordered
            if version < target_version:
                if closest_match is None or version > closest_match:
                    closest_match = version
        
        if closest_match is None:
            raise ValueError(
                f"Could not find any suitable version for target version {target_version}"
            )
        
        return closest_match
    
    def get_game_files_for_version(self, version: GameVersion) -> GameDataFiles:
        """
        Get all game data file paths for a specific version.
        
        Args:
            version: The game version to load (e.g., "0.0.11")
            
        Returns:
            GameDataFiles object with all file paths
            
        Raises:
            FileNotFoundError: If required directories or files don't exist
            ValueError: If no suitable version is found
        """
        game_files = {}
        
        for key, base_folder_name in self.BASE_FOLDER_NAMES.items():
            folder_path = os.path.join(self.folder_path, base_folder_name)
            
            if not os.path.exists(folder_path):
                raise FileNotFoundError(f"Game data folder not found: {folder_path}")
            
            # Get available versions in this folder
            versions_available = [
                d for d in os.listdir(folder_path)
                if os.path.isdir(os.path.join(folder_path, d))
            ]
            
            if not versions_available:
                raise FileNotFoundError(f"No versions found in {folder_path}")
            
            # Find the closest version
            found_version = self.get_closest_version(versions_available, version)
            
            # Construct the file path
            file_name = self.FILE_NAMES[key]
            file_path = os.path.join(folder_path, found_version, file_name)
            
            if not os.path.exists(file_path):
                raise FileNotFoundError(f"Expected file not found: {file_path}")
            
            game_files[key] = file_path
        
        # Add computed output files from tools/output/{version}/
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_dir = os.path.join(script_dir, 'output', version)
        
        for key, filename in self.COMPUTED_OUTPUT_FILES.items():
            file_path = os.path.join(output_dir, filename)
            game_files[key] = file_path
        
        return GameDataFiles(**game_files)        