#!/usr/bin/env python3
"""
Generate static JSON files from game data sources.
This script parses all game data files and outputs optimized JSON files
that can be loaded directly on the client side, avoiding Next.js hydration overhead.

IMPORTANT: Run create-adjacency-data.py BEFORE running this script!
This script depends on:
  - adjacency-data.csv (generated by create-adjacency-data.py)
  - location-river-colors.json (generated by create-adjacency-data.py)
"""

import json
import os
import csv
from typing import Dict, List, Set, Optional
from dataclasses import asdict
from game_data_loader import GameDataLoader
from game_data_utils import (
    parse_pops_file,
    parse_roads_file,
    parse_development_file,
    parse_cities_and_buildings_file,
    parse_town_setup_file,
    parse_location_templates,
    parse_location_classification,
    parse_location_hierarchy,
    parse_countries_files,
    parse_location_town_setups,
    load_color_to_name_mapping,
    hex_to_rgb,
    LocationData,
    LocationHierarchy,
    DevelopmentRules
)


def calculate_river_size_coefficient(river_hex_colors: List[str]) -> float:
    """
    Calculate river size coefficient based on river colors (1-5 scale).
    Darkest (non-red) color = 5, lightest = 1.
    
    Args:
        river_hex_colors: List of hex color strings for rivers at this location
    
    Returns:
        River size coefficient (1.0 to 5.0), or 0.0 if no rivers
    """
    if not river_hex_colors:
        return 0.0
    
    # Filter out bright red colors (errors/special markers)
    filtered_colors = []
    for hex_color in river_hex_colors:
        r, g, b = hex_to_rgb(hex_color)
        # Skip bright red (where red is dominant and high)
        if r > 200 and g < 100 and b < 100:
            continue
        filtered_colors.append((r, g, b))
    
    if not filtered_colors:
        return 0.0
    
    # Calculate brightness for each color (average of RGB)
    brightnesses = [sum(rgb) / 3 for rgb in filtered_colors]
    
    # Find the darkest river at this location
    darkest_brightness = min(brightnesses)
    
    # Define brightness bounds (these could be tuned)
    # Darkest rivers in the game (near black) ~ 30-50
    # Lightest rivers (light blue) ~ 180-220
    min_brightness = 30.0
    max_brightness = 220.0
    
    # Normalize: darker = higher coefficient
    # darkest_brightness closer to min_brightness -> coefficient closer to 5
    # darkest_brightness closer to max_brightness -> coefficient closer to 1
    if darkest_brightness <= min_brightness:
        return 5.0
    elif darkest_brightness >= max_brightness:
        return 1.0
    else:
        # Linear interpolation: darkness increases coefficient
        normalized = (max_brightness - darkest_brightness) / (max_brightness - min_brightness)
        return 1.0 + (normalized * 4.0)  # Scale to 1-5 range


def compute_location_development(
    location_name: str,
    location_data: LocationData,
    hierarchy: LocationHierarchy,
    development_rules: DevelopmentRules,
    roads_set: Set[str],
    is_coastal: bool = False,
    river_colors: List[str] = None,
    location_rank: Optional[str] = None,
    is_ownable: bool = True
) -> tuple[float, dict]:
    """
    Compute development value for a location based on development rules.
    
    Args:
        location_name: Name of the location
        location_data: LocationData with topography, vegetation, natural_harbor_suitability, etc.
        hierarchy: LocationHierarchy with continent, subcontinent, region, area, province
        development_rules: DevelopmentRules from parse_development_file
        roads_set: Set of location names that have roads (either sending or receiving)
        is_coastal: Whether location has port access (from adjacency data)
        river_colors: List of hex colors of rivers flowing through this location
        location_rank: Optional rank (city, town, etc.)
        is_ownable: Whether the location is ownable (defaults to True)
    
    Returns:
        Tuple of (development_value, breakdown_dict) where breakdown_dict contains
        the contribution from each rule category
    """
    breakdown = {
        'base': 0,
        'topography': 0,
        'vegetation': 0,
        'climate': 0,
        'rank': 0,
        'road': 0,
        'coastal': 0,
        'river': 0,
        'river_coef': 0,  # New field for river coefficient
        'region': 0,
        'area': 0,
        'province': 0,
        'unique': 0,
        'total': 0
    }
    
    # Unownable locations (sea, lakes, unpassable terrain) have 0 development
    if not is_ownable:
        return 0, breakdown
    
    development = development_rules.base
    breakdown['base'] = development_rules.base
    
    # Add topography modifier
    if location_data.topography and location_data.topography in development_rules.topography:
        value = development_rules.topography[location_data.topography]
        development += value
        breakdown['topography'] = value
    
    # Add vegetation modifier
    if location_data.vegetation and location_data.vegetation in development_rules.vegetation:
        value = development_rules.vegetation[location_data.vegetation]
        development += value
        breakdown['vegetation'] = value
    
    # Add climate modifier
    if location_data.climate and location_data.climate in development_rules.climate:
        value = development_rules.climate[location_data.climate]
        development += value
        breakdown['climate'] = value
    
    # Add location rank modifier
    if location_rank and location_rank in development_rules.locationRank:
        value = development_rules.locationRank[location_rank]
        development += value
        breakdown['rank'] = value
    
    # Add road modifier
    if location_name in roads_set:
        value = development_rules.road
        development += value
        breakdown['road'] = value
    
    # Add coastal modifier (multiplied by natural harbor suitability)
    if is_coastal:
        value = development_rules.coastal * location_data.natural_harbor_suitability
        development += value
        breakdown['coastal'] = value
    
    # Add river modifier (multiplied by river size coefficient 1-5)
    if river_colors:
        river_size_coef = calculate_river_size_coefficient(river_colors)
        value = development_rules.river * river_size_coef
        development += value
        breakdown['river'] = value
        breakdown['river_coef'] = river_size_coef
    
    # Add region modifier
    if hierarchy.region and hierarchy.region in development_rules.regions:
        value = development_rules.regions[hierarchy.region]
        development += value
        breakdown['region'] = value
    
    # Add area modifier
    if hierarchy.area and hierarchy.area in development_rules.areas:
        value = development_rules.areas[hierarchy.area]
        development += value
        breakdown['area'] = value
    
    # Add province modifier
    if hierarchy.province and hierarchy.province in development_rules.provinces:
        value = development_rules.provinces[hierarchy.province]
        development += value
        breakdown['province'] = value
    
    # Check for unique location modifier
    if location_name in development_rules.uniqueLocations:
        value = development_rules.uniqueLocations[location_name]
        development += value
        breakdown['unique'] = value
    
    breakdown['total'] = development
    return float("{:.2f}".format(development)), breakdown


def generate_game_data_json(
    version: str = "0.0.11",
    output_dir: str = None,
    source: str = "app",
    game_root_path: Optional[str] = None
):
    """
    Generate static JSON files from game data.
    
    Args:
        version: Game version to load
        output_dir: Output directory (defaults to ../public/{version}/game_data/)
        source: "app" (default) or "game"
        game_root_path: Root path to the installed game (required for source="game")
    """

    # specific values to print
    locations_to_print = ['cologne', 'paris', 'london', 'siena']

    # Setup paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    
    if output_dir is None:
        output_dir = os.path.join(project_root, "public", version, "game_data")
    
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Loading game data for version {version}...")
    
    # Load all game data files
    loader = GameDataLoader(source=source, game_root_path=game_root_path)
    files = loader.get_game_files_for_version(version)
    
    print("Parsing data files...")
    
    # Parse all data
    _, name_to_color = load_color_to_name_mapping(files.locations_color_mapping)
    color_to_name = {hex: name for name, (r, g, b) in name_to_color.items() for hex in [f'{r:02x}{g:02x}{b:02x}']}
    name_to_color_hex = {name: f'{r:02x}{g:02x}{b:02x}' for name, (r, g, b) in name_to_color.items()}
    
    location_data = parse_location_templates(files.location_data)
    
    non_ownable, impassable_mountains = parse_location_classification(files.location_classification)
    
    hierarchy = parse_location_hierarchy(files.provinces_data)

    #whitelisted_countries = {"SWE", "DAN", "NOR", "ENG", "FRA", "TEU", "BRA", "BOH", "HUN", "POL", "LIT", "MOS", "NOV", "OTT", "RUS", "CAS", "POR", "VEN", "PAP", "ARB", "MOR", "TUN", "DHL", "ARA", "HAB", "KIE", "GEO", "MAM", "OMA", "VIJ", "BYZ", "KOR" }
    # Parse countries file and load all countries (no whitelist), enriching with English names
    countries_data_map = parse_countries_files(
        files.countries_file,
        country_english_localization_file=files.country_english_localization_file,
        whitelisted_countries=None,
    )

    with open(files.location_centers_file, "r", encoding="utf-8") as centers_file:
        location_centers = json.load(centers_file)
    
    # Load new game_setup files
    print("Parsing game setup files...")
    populations = parse_pops_file(files.pops_file)
    roads = parse_roads_file(files.roads_file)
    development_rules = parse_development_file(files.development_file)
    whitelisted_buildings = {'wharf', 'fishing_village', 'dock', 'bridge_infrastructure', 'bailiff'}
    location_ranks, location_buildings = parse_cities_and_buildings_file(
        files.cities_buildings_file,
        whitelisted_buildings
    )

    town_setup_file_path = files.town_setup_file 
    town_setups = parse_town_setup_file(town_setup_file_path, whitelisted_buildings)
    location_town_setups = parse_location_town_setups(files.cities_buildings_file)
    for loc in locations_to_print:
        print(f"rank of {loc}:", location_ranks.get(loc))
        print(f"buildings of {loc}:", location_buildings.get(loc, []))
    
    # Load adjacency data and river colors
    print("Loading adjacency and river data...")
    coastal_locations = set()
    river_locations = set()
    lake_locations = set()
    
    with open(files.adjacency_data, 'r', encoding='utf-8', newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            access_type = row['accessType']
            loc_a = row['locationA']
            loc_b = row['locationB']
            
            if access_type == 'port' or access_type == 'port-river':
                # Both locations in a port connection are coastal
                coastal_locations.add(loc_a)
                coastal_locations.add(loc_b)
            elif access_type == 'river':
                # Both locations in a river connection are on a river
                river_locations.add(loc_a)
                river_locations.add(loc_b)
            elif access_type == 'lake':
                # Both locations in a lake connection are on a lake
                lake_locations.add(loc_a)
                lake_locations.add(loc_b)
    
    with open(files.river_colors, 'r', encoding='utf-8') as f:
        location_river_colors = json.load(f)
    
    print(f"Found {len(coastal_locations)} coastal locations")
    print(f"Found {len(river_locations)} river locations")
    print(f"Found {len(lake_locations)} lake locations")
    print(f"Found {len(location_river_colors)} locations with river colors")
    
    # Build set of locations with roads for quick lookup
    roads_set = set()
    for loc1, loc2 in roads:
        roads_set.add(loc1)
        roads_set.add(loc2)
    
    print("Building location data map...")
    
    # Build locationDataMap and collect development breakdowns
    location_data_map = {}
    development_breakdowns = []
    
    for location_name, data in location_data.items():
        hex_color = name_to_color_hex.get(location_name)
        if not hex_color:
            continue
        
        is_non_ownable = location_name in non_ownable
        is_impassable_mountain = location_name in impassable_mountains
        is_lake = data.topography == "lakes"
        is_sea = data.topography in [
            "ocean", "coastal_ocean", "inland_sea", 
            "ocean_wasteland", "narrows"
        ]
        
        # Get hierarchy for this location
        location_hierarchy = hierarchy.get(location_name, LocationHierarchy(
            continent="",
            subcontinent="",
            region="",
            area="",
            province=""
        ))
        
        # Get population (default to 0 if not found)
        population = populations.get(location_name, 0)
        
        # Get location rank
        rank = location_ranks.get(location_name)
        
        # Determine if location is ownable
        is_ownable = not (is_non_ownable or is_impassable_mountain or is_lake or is_sea)
        
        # Check if location is coastal
        is_coastal = location_name in coastal_locations
        
        # Get river colors for this location
        river_colors_list = location_river_colors.get(location_name, [])
        
        # Compute development with breakdown
        development, breakdown = compute_location_development(
            location_name,
            data,
            location_hierarchy,
            development_rules,
            roads_set,
            is_coastal,
            river_colors_list,
            rank,
            is_ownable
        )

        if location_name in locations_to_print:
            print(f"Development for {location_name}: {development}")
        
        # Store breakdown for CSV output
        development_breakdowns.append({
            'location': location_name,
            'ownable': is_ownable,
            'topography_type': data.topography or '',
            'vegetation_type': data.vegetation or '',
            'rank': rank or '',
            'region': location_hierarchy.region,
            'area': location_hierarchy.area,
            'province': location_hierarchy.province,
            'has_road': location_name in roads_set,
            'is_coastal': is_coastal,
            'has_river': len(river_colors_list) > 0,
            'river_coef': breakdown.get('river_coef', 0),
            **breakdown
        })
        
        # Get center coordinates for this location (precomputed by generate_location_centers.py)
        center = location_centers.get(location_name)
        center_dict = {"x": center["x"], "y": center["y"]} if center else None
        
        location_data_map[location_name] = {
            "topography": data.topography,
            "vegetation": data.vegetation,
            "climate": data.climate,
            "naturalHarborSuitability": data.natural_harbor_suitability,
            "name": location_name,
            "hexColor": hex_color,
            "isLake": is_lake,
            "isSea": is_sea,
            "ownable": is_ownable,
            "isCoastal": location_name in coastal_locations,
            "isOnRiver": location_name in river_locations,
            "isOnLake": location_name in lake_locations,
            "hierarchy": {
                "continent": location_hierarchy.continent,
                "subcontinent": location_hierarchy.subcontinent,
                "region": location_hierarchy.region,
                "area": location_hierarchy.area,
                "province": location_hierarchy.province
            },
            "centerCoordinates": center_dict,
            "population": population,
            "development": development,
            "rank": rank,
            "buildings": sorted(list(
                set(location_buildings.get(location_name, [])) |
                set(town_setups.get(location_town_setups.get(location_name, ""), []))
            ))
        }

    
    # Write development breakdown CSV for debugging
    print("Writing development breakdown CSV...")
    csv_path = os.path.join(output_dir, f"development_breakdown_{version}.csv")
    
    with open(csv_path, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['location', 'ownable', 'topography_type', 'vegetation_type', 'rank', 
                     'region', 'area', 'province', 'has_road', 'is_coastal', 'has_river', 'river_coef',
                     'base', 'topography', 'vegetation', 'climate', 'rank', 'road', 'coastal', 'river',
                     'region', 'area', 'province', 'unique', 'total']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        
        # Sort by total development for easier analysis
        sorted_breakdowns = sorted(development_breakdowns, key=lambda x: x['total'], reverse=True)
        for row in sorted_breakdowns:
            writer.writerow(row)
    
    print(f"  ✓ Development breakdown CSV: {csv_path}")
    
    print("Writing JSON files...")
    
    # Write output files
    # Convert CountryData objects to dicts for JSON serialization
    countries_data_map_serializable = {k: asdict(v) for k, v in countries_data_map.items()}
    output_files = {
        "location-data-map.json": location_data_map,
        "color-to-name-map.json": color_to_name,
        "countries-data-map.json": countries_data_map_serializable,
        "roads.json": roads
    }
    
    total_size = 0
    for filename, data in output_files.items():
        filepath = os.path.join(output_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, separators=(',', ':'))  # Compact JSON
        
        file_size = os.path.getsize(filepath)
        total_size += file_size
        print(f"  ✓ {filename}: {file_size / 1024:.1f} KB ({len(data)} entries)")
    
    print(f"\nTotal size: {total_size / 1024:.1f} KB ({total_size / 1024 / 1024:.2f} MB)")
    print(f"Output directory: {output_dir}")
    print("\n✓ Static game data generation complete!")


if __name__ == "__main__":
    import sys
    
    version = sys.argv[1] if len(sys.argv) > 1 else "0.0.11"
    
    # Default output directory: tools/output/{version}/
    if len(sys.argv) > 2:
        output_dir = sys.argv[2]
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_dir = os.path.join(script_dir, 'output', version)
    
    generate_game_data_json(version, output_dir)
